<?php
/**
 * Illia Neiman
 *
 * NOTICE OF LICENSE
 *
 * According to LICENCE file you are not allowed to copy, use or recreate this file in any ways.
 * Specially for eCommerce usage.
 *
 * @category Ineiman
 * @package RecentlyPurchased
 * @copyright Copyright (c) 2021-current Ineiman (https://github.com/illyaneiman)
 * @email kg.illya.ney@gmail.com
 */
?>
<?php
/** @var \Magento\Banner\Block\Ajax\Data $block */
/** @codingStandardsIgnoreFile */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Banner/js/model/banner":
                <?= /* @noEscape */ $this->helper(Magento\Framework\Json\Helper\Data::class)->jsonEncode([
                    'sectionLoadUrl' => $block->getCustomerDataUrl('banner/ajax/load'),
                    'cacheTtl' => $block->getCacheTtl(),
                    'categoryId' => $block->getRequest()->getParam('id')
                ]); ?>
        }
    }
</script>
