<?php
use Magento\Framework\App\Action\Action;

/** @var $block \Ineiman\RecentlyPurchased\Block\Widget */
/** @var $escaper \Magento\Framework\Escaper */
/** @codingStandardsIgnoreFile */
$items = $block->createCollection();
$image = 'product_page_image_medium';
$title = $block->getTitle();
?>
<?php if ($block->isEnabled()): ?>
    <?php if (count($items)): ?>
        <?php $type = 'widget-product-grid'; ?>
        <?php $mode = 'grid'; ?>
        <div class="block widget recently-purchased <?= /* @noEscape */ $mode; ?>">
            <div class="block-title" style="text-align: center">
                <strong role="heading" aria-level="2"><?= $escaper->escapeHtml($title); ?></strong>
            </div>
            <div class="block-content">
                <div class="products-<?= /* @noEscape */ $mode; ?> <?= /* @noEscape */ $mode; ?>">
                    <ol class="product-items <?= /* @noEscape */ $type; ?>">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $item): ?>
                            <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">'; ?>
                            <div class="product-item-info">
                                <a href="<?= $escaper->escapeUrl($block->getProductUrl($item)); ?>" class="product-item-photo">
                                    <?= $block->getImage($item, $image)->toHtml(); ?>
                                </a>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?= $escaper->escapeHtml($item->getName()); ?>"
                                           href="<?= $escaper->escapeUrl($block->getProductUrl($item)); ?>"
                                           class="product-item-link">
                                            <?= $escaper->escapeHtml($item->getName()); ?>
                                        </a>
                                    </strong>
                                    <?= $block->getProductPriceHtml($item, $type); ?>
                                    <?= $block->getProductDetailsHtml($item); ?>

                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <div class="actions-primary">
                                                <?php if ($item->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($item); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($item->getSku()); ?>" action="<?= $escaper->escapeUrl($postParams['action']); ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED; ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                        <?= $block->getBlockHtml('formkey'); ?>
                                                        <button type="submit"
                                                                title="<?= $escaper->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary">
                                                            <span><?= $escaper->escapeHtml(__('Add to Cart')); ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($item->isAvailable()): ?>
                                                        <div class="stock available"><span><?= $escaper->escapeHtml(__('In stock')); ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= $escaper->escapeHtml(__('Out of stock')); ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()): ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($item); ?>'
                                                       class="action towishlist"
                                                       data-action="add-to-wishlist"
                                                       title="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')); ?>">
                                                        <span><?= $escaper->escapeHtml(__('Add to Wish List')); ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl()): ?>
                                                    <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($item); ?>'
                                                       title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')); ?>">
                                                        <span><?= $escaper->escapeHtml(__('Add to Compare')); ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?= ($iterator == count($items) + 1) ? '</li>' : ''; ?>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
        </div>
        <?php if ($block->getBlockHtml('formkey')): ?>
            <script type="text/x-magento-init">
                {
                    ".block.widget [data-role=tocart-form]": {
                        "Magento_Catalog/js/validate-product": {}
                    }
                }
            </script>
        <?php endif; ?>
    <?php else: ?>
        <div class="block widget recently-purchased">
            <div class="block-title" style="text-align: center">
                <strong role="heading" aria-level="2"><?= $escaper->escapeHtml($title); ?></strong>
            </div>
            <div class="block-content">
                <div class="empty-content"><?= $escaper->escapeHtml(__('There are no recently purchased items')); ?></div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
